/**
 * Why not creating random quality options too? ;)
 */
export const randomQuantityOptions = [
  "millions",
  "billions",
  "trillions",
  "quadrillions",
  "quintillion",
  "sixtillions",
  "septillions",
  "eightillions",
  "nonillions",
  "nonagintillions",
  "megillions",
  "icterillions",
  "iczetillions",
  "exotillions",
  "multillions",
  "thousands",
  "hundreds",
  "dozens",
  "a community",
  "a lot",
  "an ecosystem",
  "specific kind",
  "a specific emo amount",
  "a curious amount",
  "an intellectual amount",
  "any existing amount",
  "9 variations",
  "a finite amount",
  "a very little amount",
  "an infinite amount",
  "a good amount",
  "a shameful amount",
  "a dark amount",
  "a clear amount",
  "an undentified amount",
  "a doubtful amount",
  "a certain amount",
  "a little amount",
  "a high amount",
  "a magical amount",
  "a boring amount",
  "a beautiful amount",
  "an ugly amount"
]
